/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as AuthorizedCreateRecipeIndexRouteImport } from './routes/_authorized/create-recipe/index'
import { Route as AuthorizedFavoritesIndexRouteImport } from './routes/_authorized/favorites/index'
import { Route as AuthorizedRecipesIndexRouteImport } from './routes/_authorized/recipes/index'
import { Route as AuthorizedSearchIndexRouteImport } from './routes/_authorized/search/index'
import { Route as AuthorizedRecipesRecipeIdIndexRouteImport } from './routes/_authorized/recipes/$recipeId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedCreateRecipeIndexRoute =
  AuthorizedCreateRecipeIndexRouteImport.update({
    id: '/create-recipe/',
    path: '/create-recipe/',
    getParentRoute: () => AuthorizedRoute,
  } as any)
const AuthorizedFavoritesIndexRoute =
  AuthorizedFavoritesIndexRouteImport.update({
    id: '/favorites/',
    path: '/favorites/',
    getParentRoute: () => AuthorizedRoute,
  } as any)
const AuthorizedRecipesIndexRoute = AuthorizedRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedSearchIndexRoute = AuthorizedSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedRecipesRecipeIdIndexRoute =
  AuthorizedRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AuthorizedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-recipe/': typeof AuthorizedCreateRecipeIndexRoute
  '/favorites/': typeof AuthorizedFavoritesIndexRoute
  '/recipes/': typeof AuthorizedRecipesIndexRoute
  '/search/': typeof AuthorizedSearchIndexRoute
  '/recipes/$recipeId/': typeof AuthorizedRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-recipe': typeof AuthorizedCreateRecipeIndexRoute
  '/favorites': typeof AuthorizedFavoritesIndexRoute
  '/recipes': typeof AuthorizedRecipesIndexRoute
  '/search': typeof AuthorizedSearchIndexRoute
  '/recipes/$recipeId': typeof AuthorizedRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/_authorized/create-recipe/': typeof AuthorizedCreateRecipeIndexRoute
  '/_authorized/favorites/': typeof AuthorizedFavoritesIndexRoute
  '/_authorized/recipes/': typeof AuthorizedRecipesIndexRoute
  '/_authorized/search/': typeof AuthorizedSearchIndexRoute
  '/_authorized/recipes/$recipeId/': typeof AuthorizedRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-recipe/'
    | '/favorites/'
    | '/recipes/'
    | '/search/'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-recipe'
    | '/favorites'
    | '/recipes'
    | '/search'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/_authorized/create-recipe/'
    | '/_authorized/favorites/'
    | '/_authorized/recipes/'
    | '/_authorized/search/'
    | '/_authorized/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/create-recipe/': {
      id: '/_authorized/create-recipe/'
      path: '/create-recipe'
      fullPath: '/create-recipe/'
      preLoaderRoute: typeof AuthorizedCreateRecipeIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/favorites/': {
      id: '/_authorized/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof AuthorizedFavoritesIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/recipes/': {
      id: '/_authorized/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthorizedRecipesIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/search/': {
      id: '/_authorized/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthorizedSearchIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/recipes/$recipeId/': {
      id: '/_authorized/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AuthorizedRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
  }
}

interface AuthorizedRouteChildren {
  AuthorizedCreateRecipeIndexRoute: typeof AuthorizedCreateRecipeIndexRoute
  AuthorizedFavoritesIndexRoute: typeof AuthorizedFavoritesIndexRoute
  AuthorizedRecipesIndexRoute: typeof AuthorizedRecipesIndexRoute
  AuthorizedSearchIndexRoute: typeof AuthorizedSearchIndexRoute
  AuthorizedRecipesRecipeIdIndexRoute: typeof AuthorizedRecipesRecipeIdIndexRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedCreateRecipeIndexRoute: AuthorizedCreateRecipeIndexRoute,
  AuthorizedFavoritesIndexRoute: AuthorizedFavoritesIndexRoute,
  AuthorizedRecipesIndexRoute: AuthorizedRecipesIndexRoute,
  AuthorizedSearchIndexRoute: AuthorizedSearchIndexRoute,
  AuthorizedRecipesRecipeIdIndexRoute: AuthorizedRecipesRecipeIdIndexRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRoute: AuthorizedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
